# Generated by Django 2.0.3 on 2019-11-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urunismi', models.CharField(max_length=50)),
                ('urun_content', models.CharField(max_length=400)),
            ],
        ),
    ]
