# Generated by Django 2.0.3 on 2019-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20191128_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='urun_agirlik',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Ağırlık'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='urun_boy',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Boy'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='urun_en',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='En'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='urun_yukseklik',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Yükseklik'),
        ),
    ]
