# Generated by Django 2.0.3 on 2019-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_urunler'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='urun_resmi',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotograf'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='urun_content',
            field=models.CharField(max_length=400, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='urunismi',
            field=models.CharField(max_length=50, verbose_name='Urun ismi'),
        ),
    ]
