# Generated by Django 2.0.3 on 2019-11-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191126_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='urun_agirlik',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ağırlık'),
        ),
        migrations.AddField(
            model_name='urunler',
            name='urun_boy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Boy'),
        ),
        migrations.AddField(
            model_name='urunler',
            name='urun_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='En'),
        ),
        migrations.AddField(
            model_name='urunler',
            name='urun_yukseklik',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Yükseklik'),
        ),
    ]
