# Generated by Django 2.0.3 on 2019-12-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20191201_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Başlık'),
        ),
    ]
